### ISSUE TITLE
äöü

### ISSUE THREAD

**Issue by blynx** [uplaod/LilGrotesk#2]
Hej,

I dont know if these are intentional - but i find the diaereses rather odd, too wide on the bold font:

![screen shot 2015-07-08 at 14 01 49](https://cloud.githubusercontent.com/assets/10874163/8569679/3c4547ec-257a-11e5-8c59-727e33875bcf.png)

cheers,
Steffen

**Comment by uplaod** [comment]
Hey,thanks to point that issue,
that wasn't intentional, we'll fix that asap;
